backends:
  src:
    # the "file" backend reads lines from a file and sends them as messages
    # and writes lines to a file when receiving messages
    kind: file
    token: @src@

  dst:
    kind: file
    token: /run/oxibridge/dst.txt

groups:
  test:
    src:
      readonly: true
    dst:
      writeonly: true
