# This is the configuration file for Oxibridge.
# As of right now, all fields are required.
# This may change if I ever add more platforms in the future.

# This configuration is shared between different platforms.
shared:
  discord_token: "PLACEHOLDER"
  telegram_token: "PLACEHOLDER"

# You can define multiple groups here to bridge multiple channels.
groups:
  - telegram_chat: -1001234567890
    discord_channel: 1234567890000
    discord_webhook: "WEBHOOK_URL_HERE"
